version: '3.3'
services:
  app:
    image: galacticcouncil/mrelayer:latest
    environment:
      ACALA_FROM_SEQ: '3408'
      BASE_FROM_SEQ: '249354'
      ETH_FROM_SEQ: '625934'
      MOONBEAM_RPC: https://rpc.api.moonbeam.network
      PRIVKEY: FILL THIS KEY ALWAYS
      REDIS_HOST: redis
      SOLANA_FROM_SEQ: '1379804'
      SPY_ENDPOINT: spy:7073
      SUI_FROM_SEQ: '222468'
      WORMHOLE_API_KEY: MAYBE FILL THIS KEY OR REMOVE IT
    networks:
      - default
    logging:
      driver: json-file
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
  base:
    image: galacticcouncil/mrelayer:latest
    command:
      - start:base
    environment:
      MOONBEAM_FROM_SEQ: '95331'
      PRIVKEY: FILL THIS KEY ALWAYS
      REDIS_HOST: redis
      SPY_ENDPOINT: spy:7073
      WORMHOLE_API_KEY: MAYBE FILL THIS KEY OR REMOVE IT
    networks:
      - default
    logging:
      driver: json-file
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
  eth:
    image: galacticcouncil/mrelayer:latest
    command:
      - start:eth
    environment:
      MOONBEAM_FROM_SEQ: '95532'
      PRIVKEY: FILL THIS KEY ALWAYS
      REDIS_HOST: redis
      SPY_ENDPOINT: spy:7073
      WORMHOLE_API_KEY: MAYBE FILL THIS KEY OR REMOVE IT
    networks:
      - default
    logging:
      driver: json-file
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
  redis:
    image: redis:latest
    volumes:
      - db22:/data
    networks:
      - default
    logging:
      driver: json-file
  spy:
    image: ghcr.io/wormhole-foundation/guardiand:latest
    command:
      - spy
      - --nodeKey
      - /node.key
      - --spyRPC
      - '[::]:7073'
      - --network
      - /wormhole/mainnet/2
      - --bootstrap
      - /dns4/wormhole-v2-mainnet-bootstrap.xlabs.xyz/udp/8999/quic/p2p/12D3KooWNQ9tVrcb64tw6bNs2CaNrUGPM7yRrKvBBheQ5yCyPHKC,/dns4/wormhole.mcf.rocks/udp/8999/quic/p2p/12D3KooWDZVv7BhZ8yFLkarNdaSWaB43D6UbQwExJ8nnGAEmfHcU,/dns4/wormhole-v2-mainnet-bootstrap.staking.fund/udp/8999/quic/p2p/12D3KooWG8obDX9DNi1KUwZNu9xkGwfKqTp2GFwuuHpWZ3nQruS1
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: 1000m
networks:
  default:
    driver: overlay
volumes:
  db22:
    driver: local
